### PR TITLE
Move AJ Khan to emeritus members

### PR DESCRIPTION
**Pull request by tkoyama010**
Thanks AJ Khan for your work!

### CODE REVIEW

**Comment by pavithraes** [comment]
@tkoyama010 Thanks for this PR. We can also add AJ to the "Emeritus members" section.

**Comment by tkoyama010** [comment]
@all-contributors please add @ak9999 for ideas

**Comment by tkoyama010** [comment]
@all-contributors please add @tkoyama010  for ideas

**Review by pavithraes — APPROVED** [review]
Thanks!

**Pull request merged**
